### ISSUE TITLE
TLS setup for https://www.codetriage.com/ incomplete

### ISSUE THREAD

**Issue by jhass** [codetriage/codetriage#479]
https://www.sslshopper.com/ssl-checker.html#hostname=https://www.codetriage.com/

Since you're using LetsEncrypt, the issue is that you used `cert.pem` where you likely should have used `fullchain.pem`, or if your server requires to specify intermediate certificates separately (very uncommon these days), you missed to specify `chain.pem` there.

This makes for example Github's Camo reject the connection.

**Comment by schneems** [comment]
cc @dmathieu any thoughts here?

**Comment by dmathieu** [comment]
This was fixed in dmathieu/sabayon/pull/5. Updating sabayon and renewing the certificate should fix it.

**Comment by jhass** [comment]
Ping, any progress on this? :)

**Comment by schneems** [comment]
I just got the latest from your repo and deployed then ran

```
~ $ sabayon -force
2016/06/29 00:40:07 cert.create email='<email>@gmail.com' domains='[codetriage.com www.codetriage.com]'
2016/06/29 00:40:08 [INFO] acme: Registering account for <email>@gmail.com
2016/06/29 00:40:08 [INFO][codetriage.com, www.codetriage.com] acme: Obtaining bundled SAN certificate
2016/06/29 00:40:08 [INFO][codetriage.com] acme: Trying to solve HTTP-01
2016/06/29 00:40:08 cert.validate
2016/06/29 00:40:29 cert.validated
2016/06/29 00:40:32 [INFO][codetriage.com] The server validated our request
2016/06/29 00:40:32 [INFO][www.codetriage.com] acme: Could not find solver for: dns-01
2016/06/29 00:40:32 [INFO][www.codetriage.com] acme: Could not find solver for: tls-sni-01
2016/06/29 00:40:32 [INFO][www.codetriage.com] acme: Trying to solve HTTP-01
2016/06/29 00:40:32 cert.validate
2016/06/29 00:40:53 cert.validated
2016/06/29 00:40:57 [INFO][www.codetriage.com] The server validated our request
2016/06/29 00:40:57 [INFO][codetriage.com, www.codetriage.com] acme: Validations succeeded; requesting certificates
2016/06/29 00:40:58 [INFO] acme: Requesting issuer cert from https://acme-v01.api.letsencrypt.org/acme/issuer-cert
2016/06/29 00:40:58 [INFO][codetriage.com] Server responded with a certificate.
2016/06/29 00:40:58 cert.created
2016/06/29 00:40:58 cert.updated
```

I'm still seeing https://www.sslshopper.com/ssl-checker.html#hostname=https://www.codetriage.com/ say there are problems but maybe it takes awhile for the cert validation to propagate?

**Comment by jhass** [comment]
No, there's no such thing as propagation here, looking at the validity timestamps it seems to still use the previous cert, perhaps you have to restart someting?

**Comment by miketheman** [comment]
Hit this today on Android 6.0

**Comment by schneems** [comment]
I opened a ticket on Heroku. No response yet. Probably hear back on Tuesday or so.

**Comment by schneems** [comment]
Fixed
